name: Run Unit Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
          ports:
            - 5432:5432
          env:
            POSTGRESQL_USERNAME: docker
            POSTGRESQL_PASSWORD: docker
            POSTGRESQL_DATABASE: api

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - run: npm run test:e2e

      env:
        JWT_SECRET: testing
        DATABASE_URL: "postgres://docker:docker@localhost:5432/apisolid?schema=public"